name: PyLint Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Install Requirements
      run: |
        sudo apt-get install -y python-coverage
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Check test coverage
      run: |
        nosetests --with-coverage convert2rhel/
        
    - name: Run Pylint
      run: |
        pylint convert2rhel/
