name: pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:        
  pylint_check_2_6:
    runs-on: ubuntu-latest
    container: marceloagmelo/centos6:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Requirements
      run: |
        yum --enablerepo=extras install -y epel-release
        yum install -y python-pip
        pip install pylint
        
    - name: Run Pylint Checks
      run: |
        pylint convert2rhel/
        
  pylint_check_2_7:
    runs-on: ubuntu-latest
    container: marceloagmelo/centos7:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Requirements
      run: |
        yum --enablerepo=extras install -y epel-release
        yum install -y python-pip
        pip install pylint
        
    - name: Run Pylint Checks
      run: |
        pylint convert2rhel/
